version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: atlan
      POSTGRES_PASSWORD: atlanpassword
      POSTGRES_DB: atlandb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg2://atlan:atlanpassword@db:5432/atlandb
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    # command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
