"""Add user roles

Revision ID: 1ecc82acd5b1
Revises: 9a22d930dfc9
Create Date: 2025-09-11 01:04:58.990323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecc82acd5b1'
down_revision: Union[str, Sequence[str], None] = '9a22d930dfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    userrole_enum = sa.Enum('USER', 'ADMIN', name='userrole')
    userrole_enum.create(op.get_bind())
    
    # Add the column with default value
    op.add_column('users', sa.Column('role', userrole_enum, nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
